services:
  keyclockserver:
    image: ${DOCKER_REGISTRY-}keyclockserver
    build:
      context: .
      dockerfile: KeyClockServer/Dockerfile
  keycloakdb:
    image: postgres
volumes:
  postgres_keycloakdb: