services:
  keyclockserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__Realm=demo
      - Keycloak__AdminClientId=admin-cli
      - Keycloak__AdminUser=admin
      - Keycloak__AdminPassword=admin
      - Keycloak__ClientId=dotnet-client
      - Keycloak__ClientSecret=770c8c27-9444-49a0-bc4b-ed9c7bbe66b1
      - Keycloak__Authority=http://keycloak:8080/realms/demo
    restart: always
    depends_on:
      - keycloakdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  keycloakdb:
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_keycloakdb:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    depends_on:
      - keycloakdb
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

      # Cấu hình DB
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloakdb:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak

      # Hostname (dev vẫn ok để trống, prod thì set domain)
      # - KC_HOSTNAME=auth.yourdomain.com
    ports:
      - "8085:8080"
  keyclockaspire.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__Realm=demo
      - Keycloak__AdminClientId=admin-cli
      - Keycloak__AdminUser=admin
      - Keycloak__AdminPassword=admin
      - Keycloak__ClientId=dotnet-client
      - Keycloak__ClientSecret=770c8c27-9444-49a0-bc4b-ed9c7bbe66b1
      - Keycloak__Authority=http://keycloak:8080/realms/demo
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  keyclockaspire.apiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__Realm=demo
      - Keycloak__AdminClientId=admin-cli
      - Keycloak__AdminUser=admin
      - Keycloak__AdminPassword=admin
      - Keycloak__ClientId=dotnet-client
      - Keycloak__ClientSecret=770c8c27-9444-49a0-bc4b-ed9c7bbe66b1
      - Keycloak__Authority=http://keycloak:8080/realms/demo
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
